CREATE TABLE IF NOT EXISTS users (
  id bigint PRIMARY KEY,
  user_name VARCHAR (50) UNIQUE NOT NULL,
  email_id VARCHAR (50) NOT NULL,
  phone_number VARCHAR (355) NOT NULL,
  first_name VARCHAR (355) NOT NULL,
  last_name VARCHAR (355) NOT NULL,
  address VARCHAR (355) NOT NULL
);

CREATE SEQUENCE IF NOT EXISTS seq INCREMENT BY 1 MINVALUE 1 NO MAXVALUE OWNED BY users.id;